# Generated by Django 2.2.9 on 2020-04-02 06:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('backToMain', wagtail.core.fields.RichTextField(blank=True)),
                ('heading', wagtail.core.fields.RichTextField(blank=True)),
                ('steps', wagtail.core.fields.StreamField([('Step', wagtail.core.blocks.StructBlock([('step_num', wagtail.core.blocks.RichTextBlock(required=False)), ('desc', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='desc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_card',
            field=wagtail.core.fields.StreamField([('Service_Card', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.RichTextBlock(required=False)), ('name', wagtail.core.blocks.RichTextBlock(required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
