# Generated by Django 2.2.9 on 2020-06-01 05:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0004_staticquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('top_descriptions', wagtail.core.fields.RichTextField(blank=True)),
                ('first_q', wagtail.core.fields.RichTextField(blank=True)),
                ('ten_year_q', wagtail.core.fields.RichTextField(blank=True)),
                ('gpa_q', wagtail.core.fields.RichTextField(blank=True)),
                ('country_q', wagtail.core.fields.RichTextField(blank=True)),
                ('no_test_result', wagtail.core.fields.RichTextField(blank=True)),
                ('esl_result', wagtail.core.fields.RichTextField(blank=True)),
                ('math_egl_result', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SingleResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', wagtail.core.fields.RichTextField(blank=True)),
                ('content', wagtail.core.fields.StreamField([('Content_Card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(required=False)), ('descriptionOrContent', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='staticquiz',
            name='page_ptr',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_card',
        ),
        migrations.AddField(
            model_name='homepage',
            name='resource_card',
            field=wagtail.core.fields.StreamField([('Resource_Card', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.RichTextBlock(required=False)), ('title', wagtail.core.blocks.RichTextBlock(required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SingleServicePage',
        ),
        migrations.DeleteModel(
            name='staticQuiz',
        ),
    ]
