# Generated by Django 2.2.13 on 2020-10-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_vnscquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnscquiz',
            name='q1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vnscquiz',
            name='q2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vnscquiz',
            name='q3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vnscquiz',
            name='q4',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
