# Generated by Django 2.2.9 on 2020-06-01 05:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0007_auto_20200601_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('backToMain', wagtail.core.fields.RichTextField(blank=True)),
                ('heading', wagtail.core.fields.RichTextField(blank=True)),
                ('steps', wagtail.core.fields.StreamField([('Step', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(required=False)), ('descriptionOrContent', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='resource_card',
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_card',
            field=wagtail.core.fields.StreamField([('Service_Card', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.RichTextBlock(required=False)), ('title', wagtail.core.blocks.RichTextBlock(required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SingleResourcePage',
        ),
    ]
