# Generated by Django 2.2.13 on 2020-10-08 06:22

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201008_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnscquiz',
            name='q1_result',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='this is the result if the answer is no to the previous question'),
        ),
        migrations.AddField(
            model_name='vnscquiz',
            name='q2_result',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='this is the result if the answer is no to the previous question'),
        ),
        migrations.AddField(
            model_name='vnscquiz',
            name='q3_result',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='this is the result if the answer is no to the previous question'),
        ),
        migrations.AddField(
            model_name='vnscquiz',
            name='q4_result',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='this is the result if the answer is no to the previous question'),
        ),
        migrations.AddField(
            model_name='vnscquiz',
            name='q5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vnscquiz',
            name='q5_result',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='this is the result if the answer is no to the previous question'),
        ),
    ]
