# Generated by Django 2.2.13 on 2020-10-08 13:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_vnscquiz_final_result_to_schedule_appt'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnscquiz',
            name='top_descriptions',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='use this to put a welcome message or say a little about the VNSC'),
        ),
    ]
