# Generated by Django 2.2.13 on 2020-10-09 11:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_vnscquiz_top_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnscquiz',
            name='final_result_to_schedule_appt',
        ),
        migrations.AddField(
            model_name='vnscquiz',
            name='placement_test_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='vnscquiz',
            name='waiver_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
